# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Coppel' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Coppel

  target 'CoppelTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CoppelUITests' do
    # Pods for testing
  end

end
